#!/usr/bin/env node
/**
 * Write .env.local from the current environment variables.
 *
 * For environments that supply configuration as environment variables rather
 * than a file - CI, containers, ephemeral agent workspaces - where the app
 * still expects .env.local. On a normal development machine you just create
 * .env.local by hand; this script is not needed there.
 *
 * Required keys are read from .env.example so there is one contract, not two.
 *
 * Usage:
 *   npm run env:setup
 *   npm run env:setup -- --force   # overwrite an existing .env.local
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repoRoot = new URL("..", import.meta.url);
const examplePath = fileURLToPath(new URL(".env.example", repoRoot));
const targetPath = fileURLToPath(new URL(".env.local", repoRoot));
const force = process.argv.includes("--force");

function requiredKeys() {
  return readFileSync(examplePath, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("#"))
    .map((line) => line.split("=")[0]);
}

function fail(message) {
  console.error(`\n  env:setup failed\n\n  ${message}\n`);
  process.exit(1);
}

const keys = requiredKeys();

if (keys.length === 0) {
  fail("No variables found in .env.example, so there is no contract to satisfy.");
}

if (existsSync(targetPath) && !force) {
  console.log(
    "\n  .env.local already exists - leaving it untouched.\n" +
      "  Re-run with `npm run env:setup -- --force` to overwrite it.\n"
  );
  process.exit(0);
}

const missing = keys.filter((key) => {
  const value = process.env[key];
  return typeof value !== "string" || value.trim() === "";
});

if (missing.length > 0) {
  fail(
    `Missing ${missing.length} of ${keys.length} required variables in the environment:\n\n` +
      missing.map((key) => `    - ${key}`).join("\n") +
      "\n\n  Set them in this environment's configuration, then run this again." +
      "\n  Use the project99-dev Firebase project for development - never production."
  );
}

const appEnvironment = process.env.NEXT_PUBLIC_APP_ENV?.trim();
const firebaseProjectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID?.trim();

if (appEnvironment !== "dev" || firebaseProjectId !== "project99-dev") {
  fail(
    "env:setup is for development and agent sessions only. " +
      "Set NEXT_PUBLIC_APP_ENV=dev and " +
      "NEXT_PUBLIC_FIREBASE_PROJECT_ID=project99-dev. " +
      "Production configuration belongs only in Vercel."
  );
}

const body =
  "# Generated by `npm run env:setup` from environment variables.\n" +
  "# Not committed: .gitignore excludes .env* apart from .env.example.\n" +
  keys.map((key) => `${key}=${process.env[key]}`).join("\n") +
  "\n";

writeFileSync(targetPath, body, { mode: 0o600 });

const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "unknown";
console.log(
  `\n  Wrote .env.local with ${keys.length} variables.\n` +
    `  Firebase project: ${projectId}\n`
);
